FreeSql.Tests/Context/ContextTest.cs
FreeSql/DbContext/CodeFirstFactory.cs
FreeSql/DbContext/FreeSqlBuilderExtension.cs
FreeSql/DbContext/FreeSqlContext.cs
FreeSql/DbContext/FreeSqlDbContext.cs
FreeSql/DbContext/FreeSqlDbContextExtension.cs
FreeSql/DbContext/FreeSqlDbContextFactory.cs
FreeSql/DbContext/FreeSqlDbSet.cs
FreeSql/Interface/IFreeSqlDbSet.cs

2019.1.24 update 
1、add Context and ContextFactory
2、add Context Configuration

FreeSqlContext

---

FreeSql.Tests/DataContext/SqlServer/SqlServerCollection.cs
FreeSql.Tests/DataContext/SqlServer/SqlServerFixture.cs
FreeSql.Tests/FreeSql.Tests.csproj
FreeSql.Tests/Generator/SqlServerTemplateGeneratorTest.cs
FreeSql.Tests/SqlServer/Curd/SqlServerDeleteTest.cs
FreeSql.Tests/SqlServer/Curd/SqlServerInsertTest.cs
FreeSql.Tests/SqlServer/Curd/SqlServerSelectTest.cs
FreeSql.Tests/SqlServer/Curd/SqlServerUpdateTest.cs
FreeSql.Tests/SqlServer/SqlServerAdo/SqlServerAdoTest.cs
FreeSql.Tests/SqlServer/SqlServerCodeFirstTest.cs
FreeSql.Tests/SqlServer/SqlServerDbFirstTest.cs
FreeSql.Tests/SqlServer/SqlServerExpression/ConvertTest.cs
FreeSql.Tests/SqlServer/SqlServerExpression/DateTimeTest.cs
FreeSql.Tests/SqlServer/SqlServerExpression/MathTest.cs
FreeSql.Tests/SqlServer/SqlServerExpression/OtherTest.cs
FreeSql.Tests/SqlServer/SqlServerExpression/StringTest.cs
FreeSql.Tests/SqlServer/SqlServerExpression/TimeSpanTest.cs
FreeSql.Tests/g.cs

使用SharedContext模式调整FreeSql.Tests的SqlServer连接

---

FreeSql.Tests/DataAnnotations/MySqlFluentTest.cs
FreeSql.Tests/DataAnnotations/SqlServerFluentTest.cs
FreeSql.Tests/DataContext/SqlServer/SqlServerFixture.cs
FreeSql.Tests/FreeSql.Tests.csproj

1. 测试完毕，清除数据
2. 增加SqlServerFluentTest.cs

调整SqlServer测试项目代码

---

Examples/repository_01/Controllers/SongController.cs
Examples/repository_01/PagingInfo.cs
Examples/restful/Controllers/SongController.cs
Examples/restful/PagingInfo.cs
FreeSql/FreeSql.xml
FreeSql/Interface/Curd/ISelect/ISelect0.cs
FreeSql/Interface/Curd/ISelect/ISelectGrouping.cs
FreeSql/Internal/CommonProvider/SelectProvider/Select0Provider.cs
FreeSql/Internal/CommonProvider/SelectProvider/SelectGroupingProvider.cs
FreeSql/Internal/Model/BasePagingInfo.cs

增加分页模型，方便前端直接修改PagingInfo再提交给后台，后台直接使用并返回

:rocket:增加分页模型分页及示例

---

FreeSql/Internal/CommonProvider/SelectProvider/Select0ProviderReader.cs

https://github.com/dotnetcore/FreeSql/issues/791

解决 AsType 相同表不同类型错误

---

FreeSql/FreeSqlBuilder.cs

原意可能是使用IsGenericTypeDefinition却用了IsGenericType

IsGenericTypeDefinition

---

Directory.Build.props
FreeSql.DbContext/FreeSql.DbContext.xml
FreeSql.DbContext/Properties/DbContextStrings.resx
FreeSql.Tests/FreeSql.Tests/Properties/CoreStringsTests.cs
FreeSql.Tests/FreeSql.Tests/Properties/DbContextStringsTests.cs
FreeSql.sln
FreeSql/FreeSql.xml
FreeSql/Properties/CoreStrings.resx
FreeSql/Properties/CoreStrings.zh-Hans.resx

I18n :ambulance: 增加默认的英文翻译

---

FreeSql.DbContext/FreeSql.DbContext.xml
FreeSql.Tests/FreeSql.Tests/FreeSql.Tests.csproj
FreeSql.Tests/FreeSql.Tests/Issues/1113.cs
FreeSql/FreeSql.xml
FreeSql/Internal/CommonProvider/SelectProvider/Select0Provider.cs

增加支持后可以自行拼接表达式树，方便使用。
另外可以支持例如 `System.Linq.Dynamic.Core` 第三方库解析 lambda 文本为表达式。
https://github.com/dotnetcore/FreeSql/issues/1113

DynamicFilterCustom 增加支持 Expression 返回值

---

FreeSql.Tests/FreeSql.Tests/ClickHouse/ClickHouseTest2.cs
FreeSql.Tests/FreeSql.Tests/ClickHouse/CollectDataEntity2.cs
Providers/FreeSql.Provider.ClickHouse/ClickHouseCodeFirst.cs

1.修复创建表时主键不能为Nullable错误
2.修复列名命名错误
3.修复表名命名错误
4.修复创建表时不支持复合索引错误
5.同步表结构增加同步表索引
6.修复Decimal不指定位数一直会同步此字段问题

修复ClickHouse CodeFirst表结构同步问题

---

FreeSql.Tests/FreeSql.Tests/QuestDb/Crud/QuestDbTestInsertAndUpdate.cs
FreeSql.Tests/FreeSql.Tests/QuestDb/Crud/QuestDbTestUpdate.cs
FreeSql.Tests/FreeSql.Tests/QuestDb/QuestDbTest.cs
Providers/FreeSql.Provider.QuestDb/Curd/QuestDbInsert.cs
Providers/FreeSql.Provider.QuestDb/Curd/QuestDbUpdate.cs
Providers/FreeSql.Provider.QuestDb/FreeSql.Provider.QuestDb.csproj
Providers/FreeSql.Provider.QuestDb/QuestDbContainer.cs
Providers/FreeSql.Provider.QuestDb/QuestDbDbFirst.cs
Providers/FreeSql.Provider.QuestDb/QuestDbGlobalExtensions.cs
Providers/FreeSql.Provider.QuestDb/QuestDbProvider.cs
Providers/FreeSql.Provider.QuestDb/QuestDbUtils.cs

1.Insert和Update ExecuteAffrows()增加RestAPI适配，解决【table busy】问题
2.增加ExecuteBulkCopy快速批量插入功能
3.FreeSqlBuilder增加UseQuestDbRestAPI扩展方法

QuestDb增加RestAPI解决并发问题

---

Providers/FreeSql.Provider.QuestDb/QuestDbGlobalExtensions.cs

- 解决QuestDb BulkCopy后CSV文件未删除的情况

---

Providers/FreeSql.Provider.QuestDb/QuestDbCodeFirst.cs

修复时间戳自动分表字段标记 [Column(Name="xxx")]特性CodeFirst报错问题

修复 QuestDb CodeFirst AutoSubtableAttribute/ColumnAttribute判断bug

---

FreeSql.Tests/FreeSql.Tests/DynamicEntity/DynamicEntityTest.cs
FreeSql/Extensions/DynamicEntityExtensions.cs

修复DynamicEntity特性构造函数实例化问题

---

FreeSql.Tests/FreeSql.Tests/ClickHouse/ClickHouseTest2.cs
Providers/FreeSql.Provider.ClickHouse/ClickHouseCodeFirst.cs

- 修复ClickHouse CodeFirst 多主键问题

---

FreeSql/FreeSql.xml
FreeSql/FreeSqlBuilder.cs
FreeSql/Internal/UtilsExpressionTree.cs

try fix https://github.com/dotnetcore/FreeSql/issues/1626
```c#
/// <summary>
/// 用于指定自定义实现TableEntiy 的缓存集合
/// 解决多实例下相同类型映射到不同表的问题
/// </summary>
/// <param name="factory"></param>
/// <returns></returns>
public FreeSqlBuilder UseCustomTableEntityCacheFactory(Func<ConcurrentDictionary<DataType, ConcurrentDictionary<Type, TableInfo>>> factory)
{
Utils.ChacheTableEntityFactory = factory;
return this;
}
```

Add TableEntityCacheFactory

---

Providers/FreeSql.Provider.Xugu/XuguExpression.cs

对虚谷日期格式化函数映射为date_dormat，以及对虚谷时间加函数映射为DATE_ADD。

虚谷日期格式化函数映射

---

FreeSql.DbContext/FreeSql.DbContext.xml
FreeSql.Tests/FreeSql.Tests.Provider.MySqlConnector/MySqlConnector/Curd/MySqlInsertOrUpdateTest.cs
FreeSql/Internal/CommonProvider/UpdateProvider.cs
Providers/FreeSql.Provider.MySqlConnector/FreeSqlMySqlConnectorGlobalExtensions.cs

UpdateProvider<T> 没有实现 IInsertOrUpdate<T>接口。

修复ExecuteMySqlBulkCopyAsync方法会出现空引用的异常

---

FreeSql.Tests/FreeSql.Tests/DynamicEntity/DynamicEntityTest.cs
FreeSql/Extensions/DynamicEntityExtensions.cs

修复DynamicEntity设置基类后失效问题

---

FreeSql.DbContext/FreeSql.DbContext.xml
FreeSql.Tests/FreeSql.Tests/ClickHouse/ClickhouseIssueTest.cs
FreeSql/FreeSql.xml
Providers/FreeSql.Provider.ClickHouse/Attributes/ClickHousePartitionAttribute.cs
Providers/FreeSql.Provider.ClickHouse/ClickHouseCodeFirst.cs
Providers/FreeSql.Provider.ClickHouse/ClickHouseUtils.cs
Providers/FreeSql.Provider.ClickHouse/Curd/ClickHouseUpdate.cs

修复ClickHouse 批量更新DateTime问题，增加ClickHouse表分区功能（Preview）

---

FreeSql/FreeSql.xml
FreeSql/Interface/Curd/ISelect/FieldAliasOptions.cs
FreeSql/Internal/CommonProvider/SelectProvider/Select0Provider.cs

FieldAliasOptions 新增空的别名,解决CountDistinct 问题

---

Providers/FreeSql.Provider.GBase/GBaseProvider.cs

fix-bigserial

---

FreeSql/Extensions/FreeSqlGlobalExpressionCallExtensions.cs

internal static ISqlOver<TValue> Over<TValue>(string sqlFunc) 能改为 public吗 #2071

增加 ntile(5) over (order by ...)
