dotnetcore/FreeSql

FreeSql/FreeSqlBuilder.cs, FreeSql/Internal/StringConvertType.cs, FreeSql/Internal/StringUtils.cs
用法
````csharp
new FreeSql.FreeSqlBuilder()
.UseEntityPropertyNameConvert(StringConvertType.PascalCaseToUnderscore)
.Build());
````
现在添加了6种转换类型
````csharp
public enum StringConvertType
{
/// <summary>
/// 不进行任何处理
/// </summary>
None = 0,
/// <summary>
/// 将帕斯卡命名字符串转换为下划线分隔字符串
/// <para></para>
/// BigApple -> Big_Apple
/// </summary>
PascalCaseToUnderscore,
/// <summary>
/// 将帕斯卡命名字符串转换为下划线分隔字符串，且转换为全大写
/// <para></para>
/// BigApple -> BIG_APPLE
/// </summary>
PascalCaseToUnderscoreWithUpper,
/// <summary>
/// 将帕斯卡命名字符串转换为下划线分隔字符串，且转换为全小写
/// <para></para>
/// BigApple -> big_apple
/// </summary>
PascalCaseToUnderscoreWithLower,
/// <summary>
/// 将字符串转换为大写
/// <para></para>
/// BigApple -> BIGAPPLE
/// </summary>
Upper,
/// <summary>
/// 将字符串转换为小写
/// <para></para>
/// BigApple -> …
```
=> 添加全局转换实体属性名方法

FreeSql/Internal/CommonExpression.cs
在 FreeSql\Internal\CommonProvider\UpdateProvider.cs  Line 390 还用到了一处 .Members[a].Name
可能也有问题，我没用到，就不擅自修改了。
=> 修复 .ToList(a => new DTO(a.id)) 报 未将对象引用设置到对象的实例 问题

FreeSql/Internal/CommonProvider/InsertProvider.cs
通过判断`byte[]`的长度，解决`byte[]`默认初始化为`new byte[]`的问题
=> fix: 修复byte[]类型的乐观锁初始化问题

Extensions/FreeSql.Generator/RazorModel.cs
生成的字符串格式多一个@符，在模板文件中无法判定当前生成的字段为string类型，因此修改代码实现修复转义字符bug
[JsonProperty, Column(DbType = "NVARCHAR", IsPrimary = true, IsNullable = false)]
public string syscfg_ID { get; set; } = @"";
=> 修复数据库默认值为'\'等转义字符导致生成的实体无法通过编译bug

Extensions/FreeSql.Generator/FreeSql.Generator.csproj, Extensions/FreeSql.Generator/RazorModel.cs
引入System.CodeDom库，将文本中回车，制表符等需要转义的字符，以转义字符的方式输出。
例如：
`public string SysBackupPath { get; set; } = @"C:\退税申报系统备份\";`
变为
`public string SysBackupPath { get; set; } = "C:\\退税申报系统备份\\";`
=> 代码生成器将数据库默认值写入生成cs文件时，将默认值变为转义字符写入。

Providers/FreeSql.Provider.Odbc/SqlServer/Curd/OdbcSqlServerSelect.cs, Providers/FreeSql.Provider.SqlServer/Curd/SqlServerSelect.cs
在不存在任何OrderBy的情况下.   
```skip != 0```时会生成一个默认排序给```ROW_NUMBER```   
```skip == 0```时会按照原先sql的默认排序导致的排序不一致的问题
修改:
当```skip == 0```并且不存在OrderBy的情况下生成和```skip != 0```同样的默认排序
=> 修复: sqlserver row_number排序不一致

Extensions/FreeSql.Generator/ConsoleApp.cs
1. 添加自定义模版的乱码说明（linux下执行工具时可能不会处理bom,所以写为不带bom）
2. 固定读取时为UTF8
=> 添加帮助信息和规定死UTF8编码

FreeSql.DbContext/DbSet/DbSetAsync.cs, FreeSql.DbContext/DbSet/DbSetSync.cs, FreeSql.DbContext/FreeSql.DbContext.xml, FreeSql.Tests/FreeSql.Tests/Issues/623.cs, FreeSql.Tests/FreeSql.Tests/PostgreSQL/PgArrayToMany/LazyLoadingTest .cs, FreeSql.Tests/FreeSql.Tests/PostgreSQL/PgArrayToMany/NormalTest.cs, FreeSql.Tests/FreeSql.Tests/PostgreSQL/PgArrayToMany/ObservableCollectionLazyLoadingTest.cs, FreeSql.Tests/FreeSql.Tests/PostgreSQL/PgArrayToMany/ObservableCollectionTest.cs, FreeSql.Tests/FreeSql.Tests/PostgreSQL/PostgreSQLPgArrayToManyTest .cs, FreeSql/Extensions/FreeSqlGlobalExtensions.cs, FreeSql/FreeSql.xml, FreeSql/Internal/CommonExpression.cs, FreeSql/Internal/CommonProvider/SelectProvider/Select1Provider.cs, FreeSql/Internal/Model/TableInfo.cs, FreeSql/Internal/UtilsExpressionTree.cs
=> Add PgArrayToMany Navigate Objects #1145

FreeSql.DbContext/DbSet/DbSet.cs
ISelect的ToList和First对象如果没有空的构造函数，则会在CreateEntityState的时候引发异常
以下为示例代码：
using FreeSql;
using FreeSql.DataAnnotations;
var fsql = new FreeSql.FreeSqlBuilder()
.UseConnectionString(DataType.Sqlite, "Data Source=mydata.db")
.UseAutoSyncStructure(true)
.Build();
fsql.CodeFirst.SyncStructure<MyDataEntity>();
fsql.GetRepository<MyDataEntity>().Insert(new MyDataEntity { Name = "my name" + DateTime.Now.ToString("yyyyMMddTHHmmss") });
var uowm = new UnitOfWorkManager(fsql);
using var uow = uowm.Begin();
var repository = uow.Orm.GetRepository<MyDataEntity, int>();
var firstData = await repository.Select.FirstAsync((o) => new MyDataDto(o.Id) { Name = o.Name }, default);
Console.WriteLine("Success firstData");
try
{
// MyDataDtoError因为没有MyDataDtoError()的构造函数，则会在Orm跟踪的时候引发异常。
var errorData = await …
=> fix: 无构造函数的对象不跟踪（基本上都是dto对象）

FreeSql.DbContext/DbSet/DbSet.cs, FreeSql.DbContext/DbSet/DbSetAsync.cs, FreeSql.DbContext/DbSet/DbSetSync.cs, FreeSql.DbContext/Repository/Repository/BaseRepository.cs, FreeSql/Extensions/FreeSqlGlobalExtensions.cs
当实体对象无空构造函数时:
直接使用fsql操作是正常的。
使用DbContent/Repository进行操作会引发异常。但是数据又会成功插入数据库中
以下为示例代码
using FreeSql;
using FreeSql.DataAnnotations;
var fsql = new FreeSql.FreeSqlBuilder()
.UseConnectionString(DataType.Sqlite, "Data Source=mydata.db")
.UseAutoSyncStructure(true)
.Build();
fsql.CodeFirst.SyncStructure<MyDataEntity>();
// ok
fsql.Insert(new MyDataEntity("desc") { Name = "my name fsql " + DateTime.Now.ToString("yyyyMMddTHHmmss") }).ExecuteIdentity();
try
{
// error
fsql.GetRepository<MyDataEntity>().Insert(new MyDataEntity("desc") { Name = "my name repo " + DateTime.Now.ToString("yyyyMMddTHHmmss") });
Console.WriteLine("Success InsertEntityData");
}
catch (Exception ex)
{
Console.WriteLine("Error InsertEntityData:{0}", ex.Message);
}
var uowm = new UnitOfWorkManager(fsql);
using var uow = …
=> fix: 修复实体对象无空构造函数时通过Repository操作引发异常的问题,增加Lazy改进并发

FreeSql/Internal/CommonExpression.cs
修复ManyToMany不会触发AsTable的bug，在构建多对多的子查询到时候创建了一个新的Select，但是没有继承当前Select的一些特性。可能除此以外还会有一些其他的问题。
var dbName = "aa";
var sql = fsql.Select<User>()
.AsTable((type, o) =>
{
Console.WriteLine(type.FullName);
return dbName + "." + o;
})
.Where(o => o.Roles.Any(m => m.Id == 1)).ToSql();
Console.WriteLine(sql);
public class User
{
[Column(IsIdentity = true, IsPrimary = true)]
public long Id { get; set; }
public string? Name { get; set; }
public virtual ICollection<Role> Roles { get; set; } = null!;
}
public class User_Role
{
[Column(IsIdentity = true, IsPrimary = true)]
public long Id { get; set; }
public long UserId { get; set; }
public virtual User User { get; set; } = null!;
public long RoleId { get; set; }
public virtual Role Role { get; set; } = null!;
}
public class Role
{
[Column(IsIdentity = …
=> fix: 修复ManyToMany不会触发AsTable的bug

Providers/FreeSql.Provider.MySql/MySqlCodeFirst.cs, Providers/FreeSql.Provider.Odbc/MySql/OdbcMySqlCodeFirst.cs
当库的表数量较多的时候，查询是否存在主键存在极大的延迟
key_column_usage：288s
columns: 0.033s
https://dev.mysql.com/doc/refman/5.6/en/information-schema-optimization.html
使用key_column_usage进行查询的话必须打开 .frm、.MYD 和 .MYI 文件进行检索性能极低
=> refactor: 优化判断表是否存在的查询语句

Providers/FreeSql.Provider.ClickHouse/ClickHouseCodeFirst.cs
修复ClickHouse CodeFirst创建表时如果主键不标记Column(IsNullable = false)]可能会报错的Bug
=> 修复ClickHouse CodeFirst创建表Bug

FreeSql/Internal/CommonProvider/SelectProvider/Select0ProviderReader.cs
优化当props属性过多时且有过多的属性与prop属性类型一样的时候,只需要迭代到第二次即可判断出是否等于1，无需一直迭代到全属性遍历完
=> 优化当props属性过多时的判断

Providers/FreeSql.Provider.QuestDb/QuestDbGlobalExtensions.cs
SampleBy默认会从第一条查询记录开始运算,若增加了ALIGN TO CALENDAR,则会对整点时间开始运算.
=> SampleBy增加对准日历参数

FreeSql/Extensions/AdoNetExtensions.cs
FreeSql.Provider.SqliteCore 所使用包的ado连接类名为SqliteConnection ， 与现有判断的类名大小写不一致，添加以进行兼容
=> 修复使用SqliteCore包无法使用GetCrud方法问题

FreeSql/Internal/CommonProvider/UpdateProvider.cs
说明:在开发的时候,希望代码能实现更高的复用,那么一个编辑方法,我希望在多个不同的场景都可以使用. 但是不同场景涉及的字段有时不一样的,每次都把完整的DTO实体生成出来,既繁琐,又容易出错, 于是想升级这个方法, 不想update的字段,为null就好了,这样不会影响数据库中的原有值. 只更新有实际意义的字段.
=> 添加 通过DTO 进行update的方法, 特点是,忽略值为null的属性.

FreeSql/Extensions/DynamicEntityExtensions.cs
解决动态实体创建时需要引用自身类型或存在交叉引用时无法使用正在创建的实体类问题。
测试创建一个多级区域的Area实体：
```C#
var fsql = new FreeSqlBuilder()
.UseConnectionString(DataType.Sqlite, "Data Source=|DataDirectory|\\test.db; Pooling=true;Min Pool Size=1")
.Build();
// 动态构建实体类型，树形结构，引用自身类型
var areaBuilder = fsql.CodeFirst.DynamicEntity("Area", new TableAttribute { Name = "dy_area" });
areaBuilder.Property("id", typeof(int), new ColumnAttribute { IsPrimary = true })
.Property("parentId", typeof(int?))
.Property("name", typeof(string), new ColumnAttribute { StringLength = 30 });
// builder.TypeBuilder可作为类型被引用
areaBuilder.Property("parent", areaBuilder.TypeBuilder, new NavigateAttribute { Bind = "parentId" })
.Property("children", typeof(List<>).MakeGenericType(areaBuilder.TypeBuilder), new NavigateAttribute { Bind = "parentId" });
var table …
```
=> DynamicEntity.DynamicCompileBuilder增加TypeBuilder只读属性和仅构建类型的方法

FreeSql.Tests/FreeSql.Tests/ClickHouse/ClickHouseTest3.cs, FreeSql.Tests/FreeSql.Tests/QuestDb/Crud/QuestDbTestInsertAndUpdate.cs, FreeSql.Tests/FreeSql.Tests/QuestDb/QuestDbIssue/QuestDbIssue.cs, FreeSql.Tests/FreeSql.Tests/QuestDb/QuestDbTest.cs, Providers/FreeSql.Provider.ClickHouse/ClickHouseExtensions.cs, Providers/FreeSql.Provider.QuestDb/QuestDbGlobalExtensions.cs
[QuestDb - ExecuteBulkCopy ：ExecuteQuestDbBulkCopy]
[ClickHouse - ExecuteBulkCopy ：ExecuteClickHouseBulkCopy]
为了防止引入多个Provider时 导致扩展方法冲突
=> 优化QuestDb BulkCopy 并重命名ClickHouse QuestDb BulkCopy 扩展方法名

Providers/FreeSql.Provider.ClickHouse/Curd/ClickHouseInsert.cs
修复使用clickhouse.client 7.2.2驱动进行批量插入时失败问题一=
=> 修复clickhouse批量插入失败问题

Extensions/FreeSql.Extensions.JsonMap/JsonMapCore.cs
JsonMap 使用自定义的 JsonSerializerSettings时，仅在存储数据序列化时使用了，读取数据反序列化未使用JsonSerializeSettings
=> JsonMap Deserialize surpport JsonSerializerSettings

FreeSql.Tests/FreeSql.Tests/ShenTong/ShenTongCodeFirstTest.cs, Providers/FreeSql.Provider.KingbaseES/KingbaseESCodeFirst.cs
使用的人大金仓数据库版本(`select version();`)：
```
KingbaseES V009R001C002B0014 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit
```
使用过程中发现第二次调用`fsql.CodeFirst.SyncStructure(table);` 报错，提示索引已存在，发现是判断条件判断表不存在，重复创建，发现是命名空间 `PUBLIC` 和 `pubic` 不对导致，数据库中是public，执行的sql是 PUBLIC
根据下面文档进行修改
https://bbs.kingbase.com.cn/blogDetail?postsId=trans_20646
https://bbs.kingbase.com.cn/docHtml?recId=aa82e3addd227d4354cafc2dcb1ff5db&url=aHR0cHM6Ly9iYnMua2luZ2Jhc2UuY29tLmNuL2tpbmdiYXNlLWRvYy92OC42LjcuMjQvZGV2ZWxvcG1lbnQvZGV2ZWxvcC10cmFuc2Zlci90cmFuc3BsYW50LXIzL3RyYW5zcGxhbnQtcjMtMS5odG1sI2lkOA
https://bbs.kingbase.com.cn/docHtml?recId=218c307e5f3d72bf20bb84a51859344a&url=aHR0cHM6Ly9iYnMua2luZ2Jhc2UuY29tLmNuL2tpbmdiYXNlLWRvYy92OS4xLjEuMjQvZGV2ZWxvcG1lbnQvZGV2ZWxvcC10cmFuc2Zlci90cmFuc …
=> 处理人大金仓判断 v9 版本判断为 v8r3版本报错，添加额外条件完善判断

FreeSql.Tests/FreeSql.Tests.Provider.TDengine/TDengine/TDengineCrud/TDengineCrudTest.cs, FreeSql.Tests/FreeSql.Tests.Provider.TDengine/TDengine/TDengineIssue/TDengineIssueTest.cs, Providers/FreeSql.Provider.TDengine/TDengineProvider.cs
=> 修复TDengine插入Datetime默认值查询异常

Extensions/FreeSql.Extensions.AggregateRoot/FreeSql.Extensions.AggregateRoot.csproj, Extensions/FreeSql.Extensions.BaseEntity/FreeSql.Extensions.BaseEntity.csproj, Extensions/FreeSql.Extensions.JsonMap/FreeSql.Extensions.JsonMap.csproj, Extensions/FreeSql.Extensions.LazyLoading/FreeSql.Extensions.LazyLoading.csproj, Extensions/FreeSql.Extensions.Linq/FreeSql.Extensions.Linq.csproj, Extensions/FreeSql.Extensions.ZeroEntity/FreeSql.Extensions.ZeroEntity.csproj, Extensions/FreeSql.Generator/FreeSql.Generator.csproj, FreeSql.All/FreeSql.All.csproj, FreeSql.DbContext/FreeSql.DbContext.csproj, FreeSql.Repository/FreeSql.Repository.csproj, FreeSql/FreeSql.csproj
在此 PR 之前，因为多数项目仅面向较旧的框架版本（`net46`, `netstandard2.0` 等），这导致我们无法在项目中启用 `裁剪兼容性检查器` （`IsTrimmable=true`）以及 `AOT兼容性检查器`（`IsAotCompatible=true`），此 PR 为这些项目添加了这些框架（`...;net6.0;net7.0`），并在项目中启用了这两种检查器；现在，在执行项目构建时，对应的项目会正确回报对裁剪、AOT不兼容API的调用。
此 PR 为解决 #2007 的前置条件，因为仅靠在较新框架上发布应用程序并不能涵盖所有API的使用。
=> 为各项目添加支持 `IsTrimmable` 和 `IsAotCompatible` 的框架以及属性

FreeSql.DbContext/Repository/ContextSet/RepositoryDbSet.cs, FreeSql.DbContext/Repository/Repository/BaseRepository.cs, FreeSql/Internal/CommonProvider/DeleteProvider.cs, FreeSql/Internal/CommonProvider/SelectProvider/Select1Provider.cs, FreeSql/Internal/CommonProvider/UpdateProvider.cs, FreeSql/Internal/GlobalFilter.cs
为全局过滤器添加类型支持(查询、更新、删除)，并修改相关操作(Select/Update/Delete)的过滤逻辑，确保只应用对应类型的过滤器。同时修复了RepositoryDbSet中过滤器的禁用逻辑，使其与操作类型匹配。
=> feat(GlobalFilter): 添加过滤器类型支持并优化各操作过滤逻辑，使其，可以在Select,Update,Delete使用不同的过滤器

FreeSql/Internal/UtilsExpressionTree.cs
fix:[2054](https://github.com/dotnetcore/FreeSql/issues/2054)
err：Expression.Convert(tryparseVarExpDecimal, tryparseVarExp.Type)
构建后是 (int)deciamlValue，应该是 Convert(deciamlValue, typeof(int)) 才对
ps.aot 编译时不能使用 Expression 隐式将 decimal 转成 int.. 等类型
=> fix：修复使用 microsoft.data.sqlite 驱动时，aot 异常

FreeSql/Internal/CommonProvider/SelectProvider/Select0Provider.cs, FreeSql/Internal/CommonProvider/SelectProvider/Select0ProviderReader.cs, FreeSql/Internal/CommonProvider/SelectProvider/SelectGroupingProvider.cs
fix：修复 Group 查询不支持 aot 问题 [2075](https://github.com/dotnetcore/FreeSql/issues/2075)
perf：优化非 aot 下分组查询性能（减少反射）
=> fix：修复 Group 查询不支持 aot 问题

FreeSql.DbContext/EfCoreFluentApi/EfCoreTableFluent`1.cs
修复数据库无法连接的时候，codefirst的HasData会导致SyncStructure迁移死循环调用，然后Stackoverflow异常
=> 修复数据库无法连接的时候，codefirst的HasData会导致SyncStructure迁移死循环调用，然后Stackoverflow异常
